/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ste.travian.world;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;

/**
 *
 * @author ste
 */
public class World {

    protected HashMap<String, Tile> map;
    
    private int maxX;
    private int maxY;
    private int minX;
    private int minY;
    
    private List<String> alliances;
    private boolean needAlliancesSort;

    public World() {
        map = new HashMap<String, Tile>();
        maxX = Integer.MIN_VALUE;
        maxY = Integer.MIN_VALUE;
        minX = Integer.MAX_VALUE;
        minY = Integer.MAX_VALUE;
        
        alliances = new ArrayList<String>();
        needAlliancesSort = false;
    }

    /**
     * Adds a new Tile to the world.
     * 
     * @param tile the tile to add; ignored if null
     */
    public void addTile(Tile tile) {
        if (tile == null) {
            return;
        }
        
        int x = tile.getX();
        int y = tile.getY();

        map.put(createKey(x, y), tile);
        
        if (x > maxX) {
            maxX = x;
        }
        
        if (x < minX) {
            minX = x;
        }
        
        if (y > maxY) {
            maxY = y;
        }
        
        if (y < minY) {
            minY = y;
        }
        
        if (alliances.indexOf(tile.getAlliance())<0) {
            alliances.add(tile.getAlliance());
            needAlliancesSort = true;
        }
    }

    /**
     * Returns the tile at the given coordinates
     * 
     * @param x
     * @param y
     * 
     * @return the tile at (x,y)
     */
    public Tile getTile(int x, int y) {
        return map.get(createKey(x, y));
    }
    
    /**
     * 
     * @return the max X cooridinate of the world
     */
    public int getMaxX() {
        return maxX;
    }

    /**
     * 
     * @return the min X coordinate of the world
     */
    public int getMinX() {
        return minX;
    }
    
    /**
     * 
     * @return the max Y cooridinate of the world
     */
    public int getMaxY() {
        return maxY;
    }

    /**
     * 
     * @return the min Y coordinate of the world
     */
    public int getMinY() {
        return minY;
    }
    
    /**
     * Does the map contain any tail?
     * 
     * @return
     */
    public boolean isEmpty() {
        return map.isEmpty();
    }
    
    /**
     * Returns all alliances in the world
     * 
     * @return all alliances in the world
     */
    public String[] getAlliances() {
        if (needAlliancesSort) {
            Collections.sort(alliances);
            needAlliancesSort = false;
        }
        return alliances.toArray(new String[alliances.size()]);
    }

    // ----------------------------------------------------------- Private methods
    /**
     * Create the key to use to add a tile into the map starting from a Tile 
     * object.
     * 
     * @param tile the tile for which we want the key
     * 
     * @return the generated key
     */
    private String createKey(Tile tile) {
        return createKey(tile.getX(), tile.getY());
    }

    /**
     * Create the key to use to add a tile into the map. The key is generated by
     * the tile's coordinates as follows:
     * 
     *  (x),(y)
     * 
     * @param x
     * @param y
     * 
     * @return the generated key
     */
    private String createKey(int x, int y) {
        return x + "," + y;
    }
}
